const hostOrganizations = [
  { name: "STVRS Kicks", logo: "/assets/hosts/stvrs-kicks-logo.jpeg", mission: "Helping students step into the school year with confidence through footwear and community support.", role: "At the event, STVRS Kicks helps lead footwear and clothing support so students can arrive prepared and confident.", website: "", instagram: "" },
  { name: "The Aesthetic Studios", logo: "/assets/hosts/the-aesthetic-studios-logo.jpg", mission: "Providing professional hair services that restore confidence before the first day of school.", role: "The studio coordinates inclusive hair services for girls and boys throughout the community experience.", website: "", instagram: "" },
  { name: "Salt and Light Media Production Company", logo: "/assets/hosts/salt-and-light-media-production-company-logo.png", mission: "Capturing authentic stories, producing premium media, and preserving the impact of the community for years to come.", role: "The company leads professional photo and video coverage, preserving the event’s story and long-term impact.", website: "", instagram: "" },
  { name: "Creative Friends Market", logo: "/assets/hosts/creative-friends-market-logo.png", mission: "Connecting entrepreneurs, creators, and neighborhood businesses through community collaboration.", role: "The market connects local entrepreneurs, creative businesses, community partners, and vendors to the experience.", website: "", instagram: "" },
] as const;

const hostOrganizationNames = hostOrganizations.map(({ name }) => name);

export const publication = {
  publicationTitle: "PARTNER WITH PURPOSE",
  publicationYear: 2026,
  editionLabel: "2026 Edition",
  mastheadDescriptor: "The Official Sponsorship Guide of Back To School on Main",
  eventName: "Back To School on Main",
  subtitle: "A Community Back-to-School Experience",
  tagline: "Fresh Fits. Fresh Styles. Bright Futures.",
  date: "Sunday, August 23, 2026",
  startDate: "2026-08-23T13:00:00-04:00",
  endDate: "2026-08-23T18:00:00-04:00",
  time: "1:00 PM–6:00 PM",
  city: "Richmond, Virginia",
  addresses: ["1705 E Main Street, Richmond, Virginia", "1716 E Main Street, Richmond, Virginia"],
  eventDescription: "A Richmond community back-to-school experience offering clothing distribution, inclusive hair services for girls and boys, school supplies as a secondary resource, live DJs in both buildings, community partners, and professional photo and video coverage.",
  missionStatement: "Community investment gives every student the confidence to step forward and thrive.",
  productionCredit: {
    role: "Creative Direction & Publication Design",
    studio: "Salt and Light Media Production Company",
  },
  attendanceGoal: "Approximately 50 families",
  hosts: hostOrganizations,
  coverPublisherCredits: hostOrganizationNames,
  hostLetter: {
    salutation: "Dear Community Partner,",
    pullQuote: "Every child deserves to begin the school year feeling confident, prepared, and supported.",
    paragraphs: [
      "Back To School on Main was created from a shared belief that every child deserves to enter the new school year with confidence.",
      "Sometimes that confidence begins with something as simple as a fresh outfit, a new hairstyle, the right school supplies, or the knowledge that their community is standing behind them. These moments may appear small, but they can shape how a student feels when they walk into the classroom on the first day of school.",
      "On Sunday, August 23, 2026, families from across the Richmond area will gather at 1705 E Main Street and 1716 E Main Street for a community back-to-school experience centered on preparation, encouragement, and connection.",
      "Through clothing distribution, inclusive hair services for girls and boys, school readiness resources, live music, local partnerships, and professional media coverage, our goal is to serve approximately 50 families while creating an experience that feels welcoming, uplifting, and memorable.",
      "Back To School on Main is powered by collaboration. Four Richmond organizations have come together with different skills, audiences, and resources, but one shared purpose: to invest in local students and help them begin the school year feeling seen, supported, and ready.",
      "We invite businesses, organizations, and community leaders to partner with us in bringing this vision to life.",
      "Your support will help provide resources, services, and meaningful moments that extend far beyond one afternoon.",
      "Together, we can build brighter futures—one student, one family, and one partnership at a time.",
    ],
    closing: "With gratitude,",
    signatories: hostOrganizationNames,
  },
  aboutExperience: {
    title: "About the Experience",
    eyebrow: "A Community Back-to-School Experience",
    statement: "Community investment gives every student the confidence to step forward and thrive.",
    description: "A Richmond community back-to-school experience offering clothing distribution, inclusive hair services for girls and boys, school supplies as a secondary resource, live DJs in both buildings, community partners, and professional photo and video coverage.",
    goalLabel: "Community Goal",
    goal: "Serve approximately 50 families.",
    components: ["Clothing Distribution", "Hair Services", "School Supplies", "Live DJ", "Community Partners", "Professional Media Coverage", "Local Vendors"],
  },
  emotionalFeature: {
    title: "More Than a Backpack.",
    statement: "Confidence begins long before the first school bell rings.",
    story: "Back To School on Main is about more than the items students carry into the classroom. It is about restoring confidence, creating opportunity, and making sure every child feels supported before the school year begins. A fresh haircut, a thoughtfully prepared backpack, or a moment of encouragement can change how a student enters that first day. When Richmond shows up together, practical support becomes something larger: a visible promise that every student matters and no family stands alone.",
    statistics: [
      { value: "50+", label: "Families Served" },
      { value: "4", label: "Community Partners" },
      { value: "2", label: "Historic Main Street Locations" },
      { value: "1", label: "Shared Mission" },
    ],
  },
  partnershipFeature: {
    title: "Why We Partner.",
    subhead: "Great communities are never built by one organization alone.",
    introduction: "Back To School on Main exists because organizations with different strengths chose to unite around one shared purpose: helping students begin the school year confident, prepared, and supported. Each founding partner brings a distinct form of care—from footwear and professional hair services to community connection and lasting documentation. Together, those contributions create something no single organization could build alone. This collaboration reflects a timeless civic truth: meaningful progress begins when people share responsibility, trust one another’s expertise, and place the needs of families first. Partnership is not simply how this experience is produced. It is the clearest expression of what the experience stands for.",
    pullQuote: "Every great community begins when different people choose one shared purpose.",
    transition: "Together we’ve built the foundation. The following pages show how your organization can become part of the story.",
  },
  opportunityFeature: {
    title: "Become Part of the Story.",
    subhead: "Partnership turns a shared belief into visible support for Richmond students.",
    pullQuote: "The most meaningful visibility is earned through the lives a partnership helps move forward.",
    blocks: [
      { label: "Participation, Reframed", copy: "Supporting Back To School on Main means joining a collective investment in how students enter the school year—prepared, encouraged, and surrounded by people who believe in their potential." },
      { label: "Visible Through Action", copy: "Partners become part of a credible local story shaped by service, collaboration, and meaningful connection with Richmond families." },
      { label: "Built to Endure", copy: "The experience lasts one afternoon. Its value continues through student confidence, stronger neighborhood relationships, and thoughtful media that preserves the community’s impact." },
    ],
    impactAreas: ["Student success", "Community investment", "Local collaboration", "Positive media exposure", "Long-term impact"],
    transition: "The pages ahead translate this shared purpose into clear partnership levels and considered ways to participate.",
  },
  sponsorshipIntroduction: {
    title: "Sponsorship Opportunities",
    statement: "Choose the partnership level that best aligns with your organization and the impact you want to make within the Richmond community.",
    introduction: "Every sponsorship directly strengthens the Back To School on Main experience—supporting student resources, meaningful community engagement, professional media coverage, and collaboration across Richmond’s neighborhoods.",
    pullQuote: "Every sponsorship becomes part of a student’s story.",
    tiers: [
      { name: "Community Partner", description: "A meaningful entry point for organizations ready to invest in student confidence and local connection." },
      { name: "Supporting Sponsor", description: "Expanded participation that helps strengthen resources, programming, and the family experience." },
      { name: "Presenting Sponsor", description: "A leadership-level partnership with a visible role in advancing the experience and its impact." },
      { name: "Title Partner", description: "The highest expression of shared purpose, community leadership, and long-term investment." },
    ],
    transition: "The following pages outline each partnership level in detail.",
  },
  communityPartnerFeature: {
    level: "Community Partner",
    investment: "$250",
    title: "Community Begins Here.",
    introduction: "Community Partner is designed for businesses, organizations, and civic leaders ready to make a direct, meaningful investment in Richmond families. It is an accessible point of entry with impact that is anything but small.",
    pullQuote: "The first level of partnership can be the first step toward a student’s most confident school year.",
    audience: "For organizations that believe local presence should be measured by how consistently they show up for the people around them.",
    value: "This partnership helps turn practical resources into a visible expression of care—strengthening the event while connecting your organization to a trusted community story.",
    benefits: [
      { title: "Backpack Distribution", copy: "Help place thoughtfully prepared school resources directly into students’ hands." },
      { title: "Brand Visibility", copy: "Be recognized within a polished community experience built around purpose." },
      { title: "Community Recognition", copy: "Stand alongside organizations choosing meaningful neighborhood investment." },
      { title: "Social Acknowledgement", copy: "Join the digital story before, during, and after the experience." },
      { title: "Event Signage", copy: "Receive considered on-site recognition that complements the event environment." },
      { title: "Richmond Families", copy: "Support confidence, preparation, and connection for local students and caregivers." },
    ],
  },
  supportingSponsorFeature: {
    level: "Supporting Sponsor",
    investment: "$500",
    title: "Growing Community Impact Together.",
    introduction: "Supporting Sponsors expand the reach of Back To School on Main by increasing available resources, strengthening visibility, and helping the experience serve more students and families throughout Richmond. Their participation creates momentum—turning a single day of support into a broader community presence before, during, and after the event.",
    pullQuote: "Growing together creates greater opportunities for every student we serve.",
    audience: "Organizations seeking increased visibility while making a measurable impact in the community.",
    value: "Supporting Sponsors help expand programming, improve the family experience, and increase meaningful engagement before, during, and after the event.",
    benefits: [
      { title: "Enhanced Logo Placement", copy: "Receive elevated recognition across selected event and publication touchpoints." },
      { title: "Printed Sponsor Recognition", copy: "Receive recognition in approved printed event and sponsorship materials." },
      { title: "Social Media Promotion", copy: "Be included in a broader rhythm of pre-event and post-event storytelling." },
      { title: "Event Signage", copy: "Gain increased on-site visibility within the carefully designed event environment." },
      { title: "Vendor Activation", copy: "Create a meaningful point of engagement with families and the Richmond community." },
      { title: "Impact Acknowledgment", copy: "Be recognized for helping expand resources, reach, and the overall family experience." },
    ],
  },
  presentingSponsorFeature: {
    level: "Presenting Sponsor",
    investment: "$1,000",
    title: "Leadership in Full View.",
    introduction: "Presenting Sponsors take a visible leadership role in Back To School on Main. Their investment helps shape the quality, reach, and influence of the experience—strengthening how families are served while elevating the story shared across Richmond before, during, and after the event.",
    pullQuote: "Leadership becomes meaningful when visibility is matched by responsibility.",
    audience: "Organizations prepared to lead publicly, invest deeply, and align their brand with a trusted community experience.",
    value: "Presenting Sponsors help set the standard for event quality, expand meaningful engagement, and give the community’s impact a stronger platform.",
    benefits: [
      { title: "Executive Logo Placement", copy: "Receive leadership-level recognition across approved publication and event materials." },
      { title: "Featured Publication Profile", copy: "Be highlighted within the annual publication’s partnership storytelling." },
      { title: "Dedicated Sponsor Spotlight", copy: "Receive a focused sponsor acknowledgment within the approved digital campaign." },
      { title: "Premier Event Signage", copy: "Gain priority on-site recognition within the designed event environment." },
      { title: "Signature Brand Activation", copy: "Create an elevated, approved point of engagement with students and families." },
      { title: "Priority Media Inclusion", copy: "Be represented within selected professional event documentation and recap media." },
    ],
  },
  titlePartnerFeature: {
    level: "Title Partner",
    investment: "$2,500",
    title: "A Legacy Written Together.",
    introduction: "The Title Partner stands at the center of Back To School on Main as its signature community leader. This is a long-term partnership built to transform what the experience can provide, how far its story can travel, and what Richmond students and families can carry forward for years to come.",
    pullQuote: "The most enduring partnerships do more than support a moment—they help define what becomes possible next.",
    audience: "An organization prepared to make a defining investment, lead with purpose, and build a lasting legacy alongside Richmond’s community.",
    value: "Title partnership brings vision, resources, and public leadership together—creating transformational impact while setting the standard for every partnership that follows.",
    benefits: [
      { title: "Exclusive Title Recognition", copy: "Receive signature recognition as the principal partner of Back To School on Main." },
      { title: "Event Naming Rights", copy: "Be integrated into approved event naming and principal sponsorship language." },
      { title: "Premier Brand Placement", copy: "Receive the publication’s highest approved placement across print and event materials." },
      { title: "Featured Editorial Profile", copy: "Tell your organization’s leadership story through a dedicated publication feature." },
      { title: "Executive Welcome Opportunity", copy: "Offer an approved welcome moment within the event run of show, when applicable." },
      { title: "Legacy Media + Renewal", copy: "Receive dedicated photo and video storytelling, VIP recognition, and first right of renewal." },
    ],
  },
  closingFeature: {
    title: "Your Partnership Starts Here.",
    messages: [
      "Thank you to every organization, business, and community leader considering a partnership with Back To School on Main.",
      "Your decision to stand with this experience helps Richmond students begin with confidence, gives families meaningful support, and strengthens the community connections that make lasting progress possible.",
    ],
    quote: "Great communities are built by people who choose to invest in one another.",
    email: "backtoschoolonmain@gmail.com",
  },
  contactEmail: "backtoschoolonmain@gmail.com",
  contactPhone: "",
  sponsorCommitmentForm: "",
  sponsorshipLevels: [],
  sponsorshipBenefits: [],
  inKindDonationCategories: ["Clothing", "Inclusive hair services", "School supplies", "Community resources", "Event production support"],
  pageTitles: ["Cover", "Letter From the Hosts", "About the Experience", "More Than a Backpack", "Why Partnership Matters", "Become Part of the Story", "Sponsorship Opportunities", "Community Partner", "Supporting Sponsor", "Presenting Sponsor", "Title Partner", "Your Partnership Starts Here"],
} as const;

export type Publication = typeof publication;
